name: Build and Publish .NET Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0' # oder deine gew√ºnschte Version

    - name: Restore dependencies
      run: dotnet restore SmoMultiplayerServer.sln

    - name: Build Debug Solution
      run: dotnet build "SmoMultiplayerServer.sln" --configuration Debug

    - name: Build Release Server Project
      run: dotnet build ./Server/Server.csproj -c Release --self-contained -r win-x64 -p:publishSingleFile=true

    - name: Publish Final Release
      run: dotnet publish ./Server/Server.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: published-server
        path: ./Server/bin/Release/net8.0/win-x64/publish/
